package view.template;

import java.awt.Color;
import java.awt.Font;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

public class Tabla extends javax.swing.JPanel {
    public Tabla() {
        initComponents();
        tblProductos.getTableHeader().setOpaque(false);
        tblProductos.getTableHeader().setBackground(Color.decode("#49C593"));
        tblProductos.getTableHeader().setForeground(Color.WHITE);
        tblProductos.getTableHeader().setFont(new Font("Roboto",Font.PLAIN,14));
    }

    public void setHeaders(String[] headers){
        for(int i=0;i<headers.length;i++)
            tblProductos.getColumnModel().getColumn(i).setHeaderValue(headers[i]);
        tblProductos.getTableHeader().repaint();
    }
    
    public void clearTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblProductos.getModel();
        dtm.setRowCount(0);
    }
    
    public void addRow(Vector<Object> rowData){
        DefaultTableModel dtm = (DefaultTableModel) tblProductos.getModel();
        dtm.addRow(rowData);
    }
    
    public int getSelectedRow(){;
        return tblProductos.getSelectedRow();
    }
    
    public Object getValueAt(int row, int column){
        return tblProductos.getValueAt(row, column);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(680, 580));
        setPreferredSize(new java.awt.Dimension(640, 580));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        tblProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Nombre"
            }
        ));
        tblProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblProductos.setGridColor(new java.awt.Color(255, 255, 255));
        tblProductos.setOpaque(false);
        tblProductos.setRowHeight(32);
        tblProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables

}

